baseURL = "https://harmonicoscillator101.github.io/"
locale = "zh-cn"
title = "Harmonicoscillator的个人网站"
theme = "PaperMod"
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 15
summaryLength = 140

[params]
  math = true
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowWordCounts = true
  ShowLastMod = true
  ShowToc = true
  TocOpen = true
  comments = true

[params.label]
    text = "Harmonicoscillator"
    icon = "/images/mostima.jpg"
    iconHeight = 35

[params.assets]
  custom_css = ["css/custom.css"]

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  minMatchCharLength = 1
  keys = ["title", "content", "summary"]

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Harmonicoscillator101"

[[params.socialIcons]]
  name = "email"
  url = "mailto:wzykyle101@foxmail.com"

[params.profileMode]
  enabled = true
  title = "嗨，欢迎来到我的小站！"
  imageUrl = "/images/mostima.jpg"
  imageTitle = "我的头像"
  [[params.profileMode.buttons]]
    name = "文章"
    url = "/posts/"
  [[params.profileMode.buttons]]
    name = "生活"
    url = "/life/"
  [[params.profileMode.buttons]]
    name = "关于"
    url = "/about/"

[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "life"
  name = "生活"
  url = "/life/"
  weight = 15

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 20

[[menu.main]]
  identifier = "archives"
  name = "时间轴"
  url = "/archives/"
  weight = 25

[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search/"
  weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.Search]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  notAlternative = true

[markup.goldmark.renderer]
  unsafe = true
